#!/bin/sh

#docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_BRANCH-$SOURCE_COMMIT
#docker push $DOCKER_REPO:$SOURCE_BRANCH-$SOURCE_COMMIT

echo " $DOCKER_REPO:$SOURCE_BRANCH-$SOURCE_COMMIT "

echo "$SOURCE_BRANCH - $SOURCE_COMMIT " > env.txt

cat env.txt

echo "hi"

cat Dockerfile

echo "-------"

echo " " >> Dockerfile

echo "RUN ls -a" >> Dockerfile

cat Dockerfile